### ISSUE TITLE
Since upgrade to spring data 1.3.0 cannot start application [DATAJPA-337]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-data-jpa#744]
**[Moosh Ben](https://jira.spring.io/secure/ViewProfile.jspa?name=mooshben)** opened **[DATAJPA-337](https://jira.spring.io/browse/DATAJPA-337?redirect=false)** and commented

_Note: Only happens when JAR is built with dependencies using maven assembly plugin_

Since I updated to spring data 1.3.0 (or 1.3.1) I'm getting the following exception:

```
PropertyAccessException 1: org.springframework.beans.MethodInvocationException: Property 'entityManager' threw exception; nested exception
is java.lang.NoSuchMethodError: org.springframework.data.jpa.repository.support.JpaRepositoryFactoryBean.setMappingContext(Lorg/springframe
work/data/mapping/context/MappingContext;)V
```

Exception is caused by one of my JpaRepository based classes.

I'm using hibernate 4.2.1, hibernate validator 5.0.0, spring data commons 1.5.1 .

This works perfectly on spring data 1.2.1 and also seems to work well inside eclipse.

But when building with maven assembly a JAR with dependencies it's not working anymore

---

**Affects:** 1.3.1
