### ISSUE TITLE
Entity classes loaded before EclipseLink LTW is initialized [DATAJPA-1250]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-data-jpa#1585]
**[Christoph Mack](https://jira.spring.io/secure/ViewProfile.jspa?name=cdpm)** opened **[DATAJPA-1250](https://jira.spring.io/browse/DATAJPA-1250?redirect=false)** and commented

I am currently working on a Spring Boot application using JPA with EclipseLink. After upgrading `spring-boot-starter-parent` from 1.5.2 to 2.0.0.M7 and `spring-data-commons` from 1.11.1 to 2.0.2 application startup fails with a `NoSuchMethodError` for an entity class's `_persistence_checkFetchedForSet`. This method is normally created by load-time weaving.

Looking at the order in which classes are loaded, it appears that some entity classes are loaded before the persistence unit and LTW is initialized.
It looks like the reason for this is that classes that appear as parameters of repository interfaces are now loaded when the repository bean definitions are created.

A minimal example to reproduce is https://github.com/spring-projects/spring-data-examples/tree/master/jpa/eclipselink with LTW enabled in `Application::getVendorProperties`: The `Customer` class gets loaded right after `CustomerRepository` and EclipseLink's `PersistenceWeaver` doesn't process it

---

**Affects:** 2.1 M1 (Lovelace), 2.0.2 (Kay SR2)

**Attachments:**
- [DATAJPA-1250-not-working.zip](https://jira.spring.io/secure/attachment/25353/DATAJPA-1250-not-working.zip) (_8.95 kB_)
- [DATAJPA-1250-working.zip](https://jira.spring.io/secure/attachment/25352/DATAJPA-1250-working.zip) (_8.81 kB_)

**Issue Links:**
- [DATACMNS-1263](https://jira.spring.io/browse/DATACMNS-1263) Allow configuration inspection-classloader customization
 (_**"depends on"**_)

**Referenced from:** pull request https://github.com/spring-projects/spring-data-jpa/pull/253

**Backported to:** [2.0.6 (Kay SR6)](https://github.com/spring-projects/spring-data-jpa/milestone/113?closed=1)
